modLoader="javafml"
loaderVersion="[43,)"
license="Not specified"

[[mods]]
modId="biggyboompy"
version="1.0.0"
displayName="biggyboompy"
credits="We used MCreator to make some of this mod."
displayURL="https://github.com/dragonwalker1/bigfatbump.git"
authors="Drake, MCreator"

[[dependencies.biggyboompy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




